don't fail examples that are expected to fail

diff --git a/.github/workflows/check-releasability.yml b/.github/workflows/check-releasability.yml
--- a/.github/workflows/check-releasability.yml
+++ b/.github/workflows/check-releasability.yml
@@ -340,6 +340,11 @@ jobs:
         with:
           repository: bevyengine/bevy
           ref: main
+      - name: Keep initial state
+        id: initial
+        run: |
+          initial=`toml get Cargo.toml example | jq -c '.[] | select(.name=="${{ matrix.example }}") | ."doc-scrape-examples"'`
+          echo "initial=$initial" >> $GITHUB_OUTPUT
       - name: Checkout Releasability
         uses: actions/checkout@v4
         with:
@@ -356,8 +361,23 @@ jobs:
           sudo apt-get update;
           DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libx264-164 libx264-dev
       - name: Document with scrapping example
+        id: scrape
+        continue-on-error: true
         run: |
           cargo +nightly doc -Zunstable-options -Zrustdoc-scrape-examples --no-deps
+      - name: Fail when needed
+        run: |
+          if [[ ${{ steps.initial.outputs.initial }} == "false" ]]; then
+            if [[ ${{ steps.scrape.outcome }} == "success" ]]; then
+              echo "Failure expected but succeeded"
+              exit 1
+            fi
+          else
+            if [[ ${{ steps.scrape.outcome }} == "failure" ]]; then
+              echo "Success expected but failed"
+              exit 1
+            fi
+          fi
 
   release-private-registry:
     name: Release to Private Registry
